# workflow name
name: Test

# fire on
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os-name }}
    strategy:
      matrix:
        app: ["entrando", "spritesomething"]

        # https://github.com/actions/virtual-environments
        os-name: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
        # exclude:
        #   - app: spritesomething
        #     os-name: macos-latest
        #     python-version: 3.9
        #   - app: spritesomething
        #     os-name: macos-latest
        #     python-version: "3.10"

        #   - app: spritesomething
        #     os-name: windows-latest
        #     python-version: 3.9
        #   - app: spritesomething
        #     os-name: windows-latest
        #     python-version: "3.10"

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Wheel
        run: |
          python -m pip install wheel
      - name: Run Tester
        run: |
          python ./resources/ci/common/py_tester.py ${{ matrix.app }}
      - name: Upload documents
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.app }}-${{ matrix.os-name }}-${{ matrix.python-version }}-manifests
          path: ./resources/user/manifests/*

  post:
    name: Post
    needs: test
    runs-on: ${{ matrix.os-name }}
    strategy:
      matrix:
        app: ["entrando", "spritesomething"]

        # https://github.com/actions/virtual-environments
        os-name: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
        # exclude:
        #   - app: spritesomething
        #     os-name: macos-latest
        #     python-version: 3.9
        #   - app: spritesomething
        #     os-name: macos-latest
        #     python-version: "3.10"

        #   - app: spritesomething
        #     os-name: windows-latest
        #     python-version: 3.9
        #   - app: spritesomething
        #     os-name: windows-latest
        #     python-version: "3.10"

    steps:
      - name: Download documents
        uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{ matrix.app }}-${{ matrix.os-name }}-${{ matrix.python-version }}-manifests
          path: ./resources/user/manifests
      - name: Echo download path
        run: echo ${{ steps.download.outputs.download-path }}
      - name: List downloaded files
        run: ls ${{ steps.download.outputs.download-path }}
      - name: Debug info
        run: cat ${{ steps.download.outputs.download-path }}/pipline.txt
